**Q: 1**
**Question: Create, Save, and Explore a Student DataFrame Using Pandas**

**Create a pandas DataFrame using the student data provided below**

Start with pandas imported for pandas standard libraries files work to here.Pandas short form of keyword is pd.

In [1]:
import pandas as pd

Create a New variable named as data.python dictionary process format student
details entered.**Following details below :**
Student ID,Name,Age,Marks,Grade.
All above details in List type included.
df - New varaible create and is equal to pd.
**Dataframe** is 2D labeled data structure (like a table or spreadsheet) that can hold multiple, heterogeneous columns, where each column is a Series.
Above data details is converted into dataformat of output.
Last line of df keyword is Display the output.

In [ ]:
# Create dataframe
data = {
    "StudentID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Alice","Bob","Charlie","Diana","Ethan","Fiona","George","Hannah","Ivan","Julia"],
    "Age": [20,21,19,22,20,21,23,19,22,20],
    "Marks": [88,75,92,65,78,85,70,95,60,80],
    "Grade": ["A","B","A","C","B","A","B","A","C","B"]
}

df = pd.DataFrame(data)

df

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

What the output are given files are dataframe convert into csv format name as students.csv and set the index values are false.

In [ ]:
# Save the dataframe
df.to_csv("students.csv", index=False)

df_new create a new variable and pandas read the students.csv files.
Display the dataframe new variable.(df_new)

In [ ]:
# Read the csv file
df_new = pd.read_csv("students.csv")

df_new

Dataframe top 3 data record printing process here.(Head keyword using top data's are shown).df_new.head(3).3 is 3 values mean the current process.

In [ ]:
# Explore the dataframe
df_new.head(3)

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A

Describe keyword using in pandas different process running inside.(count,mean,std,min,25%,50%,75%,max).StudentID,Age,Marks are also calculated with in different describe methods.

In [ ]:
df_new.describe()

       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean   105.50000  20.700000  78.800000
std      3.02765   1.337494  11.535453
min    101.00000  19.000000  60.000000
25%    103.25000  20.000000  71.250000
50%    105.50000  20.500000  79.000000
75%    107.75000  21.750000  87.250000
max    110.00000  23.000000  95.000000

New data frame varaible to check the "How many rows and columns do have in the dataframe".Shape keyword as using find the total num of rows and column.

In [ ]:
df_new.shape

(10, 5)

New dataframe find the datatypes ID,AGE,MARKS are integer.Name and grade are object.Python language name and grade also string.Pandas are object.

In [ ]:
df_new.dtypes

StudentID     int64
Name         object
Age           int64
Marks         int64
Grade        object
dtype: object

New dataframe find the information check using (info) keyword. Column details Null count,datatype,memory usage.

In [ ]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     object
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
 4   Grade      10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes